const ACTIONS={
    START_SEARCHING:"START_SEARCHING",
    GET_AVAILABLE_USERS:"GET_AVAILABLE_USERS",
    CREATE_GAME_WITH_USER:"CREATE_GAME_WITH_USER",
    GAME_IS_CREATE:"GAME_IS_CREATE",
    ME:"ME",
    SET_MOVING:"SET_MOVING",
    CHANGE_BOARD:"CHANGE_BOARD",
    STOP_SEARCHING: "STOP_SEARCHING",
    SET_OFFER_FOR_DRAW:"SET_OFFER_FOR_DRAW",
    OFFER_FOR_DRAW:"OFFER_FOR_DRAW",
    REJECT_OFFER_FOR_DRAW:"REJECT_OFFER_FOR_DRAW",
    SET_REJECT_OFFER_FOR_DRAW:"SET_REJECT_OFFER_FOR_DRAW",
    SET_ACCEPT_OFFER_FOR_DRAW:"SET_ACCEPT_OFFER_FOR_DRAW",
    ACCEPT_OFFER_FOR_DRAW:"ACCEPT_OFFER_FOR_DRAW",
    SET_GIVE_UP:"SET_GIVE_UP",
    GIVE_UP:"GIVE_UP",
    OPPONENT_DISCONNECT:"OPPONENT_DISCONNECT",
    RECONNECT_FOR_GAME: "RECONNECT_FOR_GAME",
    SEND_MESSAGE:"SEND_MESSAGE"
}
export default ACTIONS
